export const data = {
    "equipment_code":"dsadsa",
    "date": "12-2-1221",
    "client":"jorge",
    "maintenance_type":"sdasdasd",
    "brand":"sdasd",
    "model":"sadsd",
    "equipment_name":"dsadsa",
    "capacity":"ffff333",
    "equipment_type":"2323",
    "observations":"",
  
    "technical_data_and_measurements":{
      "drive_unit":{
        "plate_data":{
          "w":"20",
          "vol":"sa",
          "amp":"sas",
          "rpm":"wqw"
        },
        "voltage_measurements":{
          "val_1":"",
          "val_2":"",
          "val_3":""
        },
        "amperage":{
          "l1":"",
          "l2":"",
          "l3":""
        }
      }
    },
    "compressor_unit":{
      "plate_data":{
        "1":{
          "hp":"",
          "vol":"",
          "amp":""
        },
        "2":{
          "hp":"",
          "vol":"",
          "amp":""
        }
      },
      "voltage_measurements":{
        "1":{
          "vl1_l2":"",
          "vl2_l3":"",
          "vl3_l1":""
        },
        "2":{
          "vl1_l2":"",
          "vl2_l3":"",
          "vl3_l1":""
        }
      },
      "amperage":{
        "1":{
          "l1":"",
          "l2":"",
          "l3":""
        },
        "2":{
          "l1":"",
          "l2":"",
          "l3":""
        }
      },
      "pressures":{
        "1":{
          "tall":"",
          "low":""
        },
        "2":{
          "tall":"",
          "low":""
        }
      }
    },
    "capacitor motor":{
      "plate_data":{
        "1":{
          "hp":"",
          "vol":"",
          "amp":"",
          "rpm":""
        },
        "2":{
          "hp":"",
          "vol":"",
          "amp":"",
          "rpm":""
        }
      },
      "measurements":{
        "1":{
          "vl1_l2":"",
          "vl2_l3":"",
          "vl3_l1":""
        },
        "2":{
          "vl1_l2":"",
          "vl2_l3":"",
          "vl3_l1":""
        }
      },
      "amperage":{
        "1":{
          "l1":"",
          "l2":"",
          "l3":""
        },
        "2":{
          "l1":"",
          "l2":"",
          "l3":""
        }
      }
    },
    "work_and_revisions_carried_out":{
      "drive_unit":{
        "interior_exterior_cleaning":{
          "ef":false,
          "com":false,
          "n_a":false
        },
        "coil_serpentines":{
          "ef":false,
          "com":false,
          "n_a":false
        },
         "adjust_prisoners_of_chumaceras":{
          "ef":false,
          "com":false,
          "n_a":false
        },
        "air_filter_wash":{
          "ef":false,
          "com":false,
          "n_a":false
        },
        "belt_tension":{
          "ef":false,
          "com":false,
          "n_a":false
        },
        "changing_straps":{
          "ef":false,
          "com":false,
          "n_a":false
        },
        "bearing_review":{
          "ef":false,
          "com":false,
          "n_a":false
        },
        "internal_insulation_review":{
          "ef":false,
          "com":false,
          "n_a":false
        },
        "Filter_change":{
          "ef":false,
          "com":false,
          "n_a":false
        },
        "overall_screw_adjustment":{
          "ef":false,
          "com":false,
          "n_a":false
        },
        "revision_of_expansion_valves":{
          "ef":false,
          "com":false,
          "n_a":false
        },
        "review_electrical_accessories":{
          "ef":false,
          "com":false,
          "n_a":false
        },
        "bimetallic_relay_revision":{
          "ef":false,
          "com":false,
          "n_a":false
        },
        "electronic_board_cleaning":{
          "ef":false,
          "com":false,
          "n_a":false
        },
        "thermostat_check":{
          "ef":false,
          "com":false,
          "n_a":false
        },
        "engine_inspection":{
          "ef":false,
          "com":false,
          "n_a":false
        },
        "drain_cleaning":{
          "ef":false,
          "com":false,
          "n_a":false
        }
      },
      "condensing_unit":{
        "interior_exterior_cleaning":{
          "ef":false,
          "com":false,
          "n_a":false
        },
        "coil_serpentines":{
          "ef":false,
          "com":false,
          "n_a":false
        },
        "bearing":{
          "ef":false,
          "com":false,
          "n_a":false
        },
        "compressor_overhaul":{
          "ef":false,
          "com":false,
          "n_a":false
        },
        "support_status":{
          "ef":false,
          "com":false,
          "n_a":false
        },
        "overall_screw_adjustment":{
          "ef":false,
          "com":false,
          "n_a":false
        },
        "review_electrical_accessories":{
          "ef":false,
          "com":false,
          "n_a":false
        },
        "bimetallic_relay_revision":{
          "ef":false,
          "com":false,
          "n_a":false
        },
        "refrigerant_pipe_inspection":{
          "ef":false,
          "com":false,
          "n_a":false
        } 
      },
      "air_distribution_system":{
        "damper_revision":{
          "ef":false,
          "com":false,
          "n_a":false
        },
        "inspection":{
          "ef":false,
          "com":false,
          "n_a":false
        },
        "thermometer_review":{
          "ef":false,
          "com":false,
          "n_a":false
        },
        "general_inspection_ducts":{
          "ef":false,
          "com":false,
          "n_a":false
        }
      }
      
    },
    "air_outlet_dampers":{
      "temperature":{
        "c":"21"
      },
      "type_of_refrigerant":"not",
      "equipment delivery conditions":{
        "ef":false,
        "com":false
      },
      "delivery_of_clean_work_area":{
        "ef":false,
        "com":false
      }
    },
    "pressure_uma_pre_mtto":{
      "parameter":{
        "35":false,
        "65":false,
        "95":false
      }
    },
    "pressure_uma_pos_mtto":{
      "parameter":{
        "35":false,
        "65":false,
        "95":false
      }
    }
  }
  
  